services:
  manager:
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"

# source 8080
# 80(lb) -> 8081(lb2) -> 8080(manager)

  lb:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"

  lb2:
    image: caddy:latest
    volumes:
      - ./Caddyfile2:/etc/caddy/Caddyfile
    expose:
      - 8081
