name: Bring up service to check if it can run

on: push

jobs:
    docker-compose:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-go@v4
          with:
            go-version: 'stable'
        - run: go install github.com/rakyll/hey@latest
        - uses: actions/checkout@v3
        - run: go run .
        - name: Docker Compose setup
          run: docker compose up --wait --detach --quiet-pull
        - name: Dump docker container logs on failure
          if: failure()
          run: docker compose logs
        - name: Load test
          run: hey http://localhost:8080
        - name: Load test via proxies
          run: hey http://localhost:8081
        - run: make clean
        - run: go run . -n 2
        - run: docker compose up --wait --detach --quiet-pull
        - name: Load test
          run: hey http://localhost:8080
        - name: Load test via proxies 2
          run: hey http://localhost:8081
        - run: make clean
        - run: go run . -n 5
        - run: docker compose up --wait --detach --quiet-pull
        - name: Load test
          run: hey http://localhost:8080
        - name: Load test via proxies 5
          run: hey http://localhost:8081
